# ~/.config/kitty/themes/oceanic-next.conf
# Oceanic Next inspired Kitty theme

foreground              #d8dee9
background              #1b2b34
selection_foreground    #ffffff
selection_background    #4f5b66

cursor                  #c0c5ce
cursor_text_color       #1b2b34

url_color               #6699cc

active_border_color     #6699cc
inactive_border_color   #343d46
bell_border_color       #ec5f67

active_tab_foreground   #1b2b34
active_tab_background   #6699cc
inactive_tab_foreground #c0c5ce
inactive_tab_background #343d46
tab_bar_background      #1b2b34

# black
color0                  #1b2b34
color8                  #65737e

# red
color1                  #ec5f67
color9                  #ec5f67

# green
color2                  #99c794
color10                 #99c794

# yellow
color3                  #fac863
color11                 #fac863

# blue
color4                  #6699cc
color12                 #6699cc

# magenta
color5                  #c594c5
color13                 #c594c5

# cyan
color6                  #5fb3b3
color14                 #5fb3b3

# white
color7                  #c0c5ce
color15                 #d8dee9
